language: go

go:
  - "1.10.x"

install:
   - glide install --strip-vendor

script:
  - go build -o executor dce/main.go

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
