launchtask:
   podmonitorinterval: 10000
   composehttptimeout: 300
   pullretry: 3
   maxretry: 3
   retryinterval: 10000
   timeout: 500000
plugins:
   pluginorder: general
cleanpod:
   timeout: 20
   unhealthy: true
   cleanvolumeandcontaineronmesoskill: true
   cleanimageonmesoskill: true
dockerdump:
   enable: true
   dumppath: /home/ubuntu
   dockerpidfile: /var/run/docker.pid
   containerpidfile: /run/docker/libcontainerd/docker-containerd.pid
   dockerlogpath: /var/log/upstart/docker.log
dockercomposeverbose: true
